# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd0dac0853362872aa90f2c5db74efe966fcae34b553bbd5de1732683e8dcae4f570ec2c87673780a4dff3feef987ff7bd9797848a36851e26896149ebf32b0f

test:
  secret_key_base: 559fc7d4db07bec99be11cedcd15742b14e32fe4926ef6b432c68bf886ae70e01ca3c39dd1f2e9840426eae793f58324f5ed67f4f8f5cdd75dd03f317141e5d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
